title = "Weblog"
Title = "Weblog"
baseURL = "http://localhost:8080"
paginate = 10
canonifyURLs = true
disableHugoGeneratorInject = true

[services.rss]
    limit = 10

[author]
    name = "Daniel Apatin"
    email = "rss@apatin.ru"

[params]
    accent = "red"
    showBorder = true
    backgroundColor = "white"
	copyright = "Daniel Apatin"

[outputs]
    home = ["HTML", "RSS"]

[outputFormats]
    [outputFormats.html]
        minify = true
    [outputFormats.css]
        minify = true
    [outputFormats.js]
        minify = true
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName = "rss"

[permalinks]
tags = "/t/:slug/"